[package]
name = "rustainer"
version = "0.1.0"
edition = "2021"
description = "A lightweight container management UI built in Rust"
authors = ["Andrew O", "Rustainer Team"]

[dependencies]
# HTTP server and routing
axum = "0.6.18"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["cors", "trace", "fs"] }

# Docker API client
bollard = "0.14.0"

# Async runtime
tokio = { version = "1.28.2", features = ["full"] }

# Serialization/Deserialization
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# Error handling
thiserror = "1.0.40"
anyhow = "1.0.71"

# Utilities
chrono = { version = "0.4.24", features = ["serde"] }
futures = "0.3.28"
async-stream = "0.3.5"