version: '3'

services:
  rustainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "801:801"  # Admin UI HTTP
      - "4431:4431"  # Admin UI HTTPS
      - "80:80"  # Service Proxy HTTP
      - "443:443"  # Service Proxy HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped